postgres:
  image: postgres
  environment:
    POSTGRES_USER: pg
    POSTGRES_PASSWORD: password

app:
  build: .
  links:
    - postgres
  volumes:
    - .:/usr/src/app
  ports:
    - "3000:3000"
  environment:
    # RAILS_ENV: development
    SESSION_SECRET: sekret

